# Generated by Django 3.0.8 on 2020-12-30 22:51

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20201230_2102'),
    ]

    operations = [
        CreateExtension(name="tablefunc")
    ]
